// MONARK — "flat" ESLint configuration, ADR-M003 D9 + addendum D9 ter (2026-09-06).
//
// STATUS: EXECUTABLE and MEASURED (TS 6.0.3, classic compiler API) — the toolchain blocker
// (NATIVE TS 7 port without the classic API) is resolved by addendum D9 (2026-09-05, option c:
// typescript pinned 6.0.3). The SCOPE of the violations is settled by addendum D9 ter:
//
//   §2  no-floating-promises: handled by the DOCUMENTED option `allowForKnownSafeCalls` targeting
//       test()/describe()/it() of `node:test` — the promise returned by the runner is handled by
//       the runner (idiom), it is NOT a code defect. The rule is KEPT as an error everywhere
//       else (no disabling). Doc: https://typescript-eslint.io/rules/no-floating-promises/
//       (verified 2026-09-06; plugin @typescript-eslint/eslint-plugin@8.69.0, schema contains
//       `allowForKnownSafeCalls`; "package" form = { from:"package", name:[...], package:"node:test" }).
//
//   §3  test files (**/*.test.ts, test/**): the 6 no-unsafe-*/no-explicit-any rules set to `off`
//       (JSON fixtures handled as `any` in the tests), WITH the measured ratchet `scripts/lint-ratchet.mjs`
//       that RE-ENABLES them on the tests and bounds the count to the committed ceiling `lint-ratchet.json`.
//       The list of the 6 rules is the SINGLE SOURCE `lint-ratchet.json` -> no possible divergence
//       between this config (off) and the ratchet (re-enable/count). Formed pending (D9 ter §3):
//       typing of the test fixtures, target ceiling 0 before a later phase.
//
// Installed versions, pinned EXACT (npm registry, R-8):
//   eslint@10.10.0  ·  typescript-eslint@8.69.0  ·  typescript@6.0.3
import tseslint from "typescript-eslint";
import ratchet from "./lint-ratchet.json" with { type: "json" };

// Off-map of the 6 deferred-typing rules in the tests — DERIVED from lint-ratchet.json (single source).
const testDeferredOff = Object.fromEntries(ratchet.rules.map((r) => [r, "off"]));

export default tseslint.config(
  // The type-checked linter only sees the project's TypeScript; out-of-program JS/MJS/CJS are ignored.
  // Lot F-public: also ignore installed deps / Next build output anywhere, and next-env.d.ts (generated by
  // `next build`, matches the apps/**/*.ts glob below and its triple-slash refs are lint bait).
  {
    ignores: [
      "node_modules/**",
      "**/node_modules/**",
      "dist/**",
      "**/*.js",
      "**/*.mjs",
      "**/*.cjs",
      "**/.next/**",
      "**/.turbo/**",
      // Declaration files carry no runtime code and must not be type-checked-linted: a *.d.ts/*.d.mts
      // outside the tsconfig program (e.g. scripts/grep-forbidden.d.mts, the vocab-gate type surface
      // for the root test — Lot F-2b) otherwise crashes the type-info rules ("no parserServices").
      "**/*.d.ts",
      "**/*.d.mts",
    ],
  },
  ...tseslint.configs.recommendedTypeChecked,
  {
    files: ["**/*.ts"],
    // apps/site stays OUT of the root TS program (its own tsconfig; not in tsconfig.json `include`):
    // pointing the type-checked project at a site .ts not in the program would emit a "parserServices"
    // fatal that fails scripts/lint-ratchet.mjs closed. It is handled by the disableTypeChecked block
    // appended at the end. apps/harness (Lot H1) IS a node package in the root program (tsconfig
    // `include` carries apps/harness/src + test), so it is type-checked-linted like packages/*.
    ignores: ["apps/site/**"],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // D9 ter §2 — node:test: test()/describe()/it() return a promise HANDLED by the runner.
      // Rule kept as an error; only these known-safe calls are exempted.
      "@typescript-eslint/no-floating-promises": [
        "error",
        {
          allowForKnownSafeCalls: [
            { from: "package", name: ["test", "describe", "it"], package: "node:test" },
          ],
        },
      ],
    },
  },
  {
    // D9 ter §3 — test files: 6 no-unsafe-*/no-explicit-any rules OFF (fixtures as any).
    // Tracked by the ratchet scripts/lint-ratchet.mjs (re-enable + ceiling). Globs = those of the ADR.
    files: ["**/*.test.ts", "test/**"],
    rules: testDeferredOff,
  },
  // Lot F-public (ADR-M004 D10 / PLAN F-1 item 8) — apps/site (Next.js) is covered by the ROOT
  // `npm run lint` yet is NOT part of the root TS program (tsconfig `include` stays packages + test).
  // Type-checked rules need a program; disableTypeChecked turns them off AND sets
  // parserOptions.project:false (measured shape: keys name/rules/languageOptions), which is what avoids
  // the "parserServices" fatal that would fail scripts/lint-ratchet.mjs closed. Net effect: apps/site is
  // linted syntactically; its numeric-honesty is enforced by test/site-honesty.test.ts (test 44). The
  // test-debt ratchet is unaffected — apps/** match neither `**/*.test.ts` nor `test/**`, so they add 0
  // to the committed ceiling (which must stay 92). Appended LAST so it wins for apps files.
  {
    files: ["apps/site/**/*.{ts,tsx}"],
    ...tseslint.configs.disableTypeChecked,
  },
);
