// MONARK Dojo -- PR-1a T-2 and T-3 oracles (ADR-DOJO-SNAPSHOT-1 section 6, PR-1a, l.364-365): owner class by the
// Ed25519 curve test, Merkle root and inclusion proofs. The references are recoded here from the FAITS read before this
// lot (docs/dojo/FAITS-pr1a-lectures-2026-09-26.md: section 1, RFC 6962 s2.1 = RFC 9162 s2.1.1; section 2, the
// reference is_on_curve of curve25519-dalek), never from the module. No network; keys are generated at run time.
import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash, generateKeyPairSync } from "node:crypto";
import { base58Decode, ed25519OnCurve, ownerClass, leafHash, nodeHash, rootOf, proofOf, verifyProof } from "../scripts/dojo-core.mjs";

// ---- reference is_on_curve, recoded (FAITS section 2): bit 255 masked, y reduced mod p and never rejected,
// u = y^2 - 1, v = d y^2 + 1, on the curve iff u = 0 or (v != 0 and u / v is a square) ----
const p = 2n ** 255n - 19n;
const md = (a: bigint): bigint => ((a % p) + p) % p;
function pw(base: bigint, e: bigint): bigint {
  let r = 1n;
  let x = md(base);
  for (let k = e; k > 0n; k >>= 1n) {
    if (k & 1n) r = (r * x) % p;
    x = (x * x) % p;
  }
  return r;
}
const inv = (a: bigint): bigint => pw(a, p - 2n);
const d = md(-121665n * inv(121666n)); // RFC 8032 s5.1 Table 1 (FAITS L-13), also anchored below on node:crypto keys
const isSquare = (a: bigint): boolean => md(a) === 0n || pw(a, (p - 1n) / 2n) === 1n;
function refOnCurve(low255: bigint): boolean {
  const y = md(low255);
  const u = md(y * y - 1n);
  const v = md(d * y * y + 1n);
  return u === 0n || (v !== 0n && isSquare(md(u * inv(v))));
}
function enc(y: bigint, sign = false): Uint8Array {
  const b = new Uint8Array(32);
  for (let i = 0; i < 32; i++) b[i] = Number((y >> BigInt(8 * i)) & 255n);
  if (sign) b[31] = (b[31] ?? 0) | 0x80;
  return b;
}
const B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function b58encode(bytes: Uint8Array): string {
  let x = 0n;
  for (const byte of bytes) x = (x << 8n) | BigInt(byte);
  let s = "";
  while (x > 0n) {
    s = (B58[Number(x % 58n)] ?? "") + s;
    x /= 58n;
  }
  for (const byte of bytes) {
    if (byte !== 0) break;
    s = "1" + s;
  }
  return s;
}

test("dojo_owner_class_is_the_ed25519_curve_test", () => {
  // FAITS section 2 vectors: base point y = 4/5 (RFC 8032 s5.1 Table 1, FAITS L-13) on; y = 2 off (3 / (4d + 1) not square); y = 1
  // canonical, as 2^255 - 18 (= p + 1, decoded to 1 by from_bytes) and with the sign bit: on (u = 0).
  assert.equal(ed25519OnCurve(enc(md(4n * inv(5n)))), true);
  assert.equal(isSquare(md(3n * inv(md(4n * d + 1n)))), false);
  assert.equal(ed25519OnCurve(enc(2n)), false);
  assert.equal(ed25519OnCurve(enc(1n)), true);
  assert.equal(ed25519OnCurve(enc(p + 1n)), true);
  assert.equal(ed25519OnCurve(enc(1n, true)), true);
  assert.equal(ed25519OnCurve(enc(p + 2n)), false);
  assert.equal(ed25519OnCurve(enc(p)), true); // non-canonical 0: -1 is a square mod p
  // the nineteen non-canonical encodings y in [p, 2^255), with and without the sign bit, and y below 200
  for (let y = p; y < 2n ** 255n; y++) for (const s of [false, true]) assert.equal(ed25519OnCurve(enc(y, s)), refOnCurve(y), String(y));
  for (let y = 0n; y < 200n; y++) assert.equal(ed25519OnCurve(enc(y, y % 2n === 0n)), refOnCurve(y), String(y));
  // first-hand anchor: Ed25519 public keys generated by node:crypto are curve points
  for (let i = 0; i < 64; i++) {
    const x = generateKeyPairSync("ed25519").publicKey.export({ format: "jwk" }).x;
    assert.ok(typeof x === "string");
    assert.equal(ed25519OnCurve(Uint8Array.from(Buffer.from(x, "base64url"))), true);
  }
  // control addresses (D-6 l.207, full forms l.57): creator and lock contract on the curve; bonding curve, its
  // associated account and the pool off the curve, as their roles [2nd] suggest (M3)
  const control: [string, string][] = [
    ["BQPsJEawxaostAfQ3USyLBHkdLiEQ46Py6CkDFHyk3QV", "holder"],
    ["2v82mDXA1cpm9yba5cnJX6gjr9b4wxMd3wsJfoRy1m6F", "program"],
    ["6tW6Vb8mwoKHhRommxq4TLwMUTdBfgKMKFKfwyFMyYWo", "program"],
    ["GhCGq9qTCBWZvpBY4fzfvxvENWe1syryLuGACgj3Lhvg", "program"],
    ["63dKEiLjxBHg3ZGTy4ApyAcJYFgePrPNr4s46RNVb1Pn", "holder"],
  ];
  for (const [address, klass] of control) {
    const bytes = base58Decode(address);
    assert.equal(bytes.length, 32);
    assert.equal(b58encode(bytes), address);
    assert.equal(ownerClass(address), klass, address);
  }
  assert.equal(ownerClass("11111111111111111111111111111111"), "holder"); // 32 zero bytes: y = 0
  for (let i = 0; i < 64; i++) {
    const bytes = Uint8Array.from(createHash("sha256").update(String(i)).digest());
    if (i % 4 === 0) bytes.fill(0, 0, 1 + (i % 3));
    assert.deepEqual(base58Decode(b58encode(bytes)), bytes);
    assert.equal(ownerClass(b58encode(bytes)), refOnCurve(BigInt("0x" + Buffer.from(bytes).reverse().toString("hex")) & ((1n << 255n) - 1n)) ? "holder" : "program");
  }
  assert.throws(() => ownerClass("0OIl"), /base58/);
  assert.throws(() => ownerClass("1" + "BQPsJEawxaostAfQ3USyLBHkdLiEQ46Py6CkDFHyk3QV"), /32 bytes/);
  assert.throws(() => ed25519OnCurve(new Uint8Array(31)), /32 bytes/);
  assert.throws(() => base58Decode(""), /non-empty/);
});

// ---- Merkle tree hash, recoded (FAITS section 1: RFC 6962 s2.1) ----
function H(...parts: Uint8Array[]): Buffer {
  const h = createHash("sha256");
  for (const x of parts) h.update(x);
  return h.digest();
}
const ZERO = Buffer.of(0);
const ONE = Buffer.of(1);
const utf8 = (s: string): Buffer => Buffer.from(s, "utf8");
function mthRef(items: Buffer[]): Buffer {
  if (items.length === 0) return H();
  if (items.length === 1) return H(ZERO, items[0] ?? Buffer.alloc(0));
  let k = 1;
  while (k * 2 < items.length) k *= 2;
  return H(ONE, mthRef(items.slice(0, k)), mthRef(items.slice(k)));
}
// Inclusion check of RFC 9162 s2.1.3.2, recoded (G1 journal: steps beyond the FAITS quote, question Q-5).
function verify9162(leaf: Buffer, index: number, size: number, path: Buffer[], root: Buffer): boolean {
  if (index >= size) return false;
  let fn = index;
  let sn = size - 1;
  let r = leaf;
  for (const q of path) {
    if (sn === 0) return false;
    if ((fn & 1) === 1 || fn === sn) {
      r = H(ONE, q, r);
      while ((fn & 1) === 0 && fn !== 0) {
        fn >>= 1;
        sn >>= 1;
      }
    } else {
      r = H(ONE, r, q);
    }
    fn >>= 1;
    sn >>= 1;
  }
  return sn === 0 && r.equals(root);
}

test("dojo_merkle_root_and_proofs", () => {
  const lines = Array.from({ length: 33 }, (_, i) => JSON.stringify({ address: "a" + String(i), hold: String(i * 7) }));
  assert.equal(leafHash("x"), H(ZERO, utf8("x")).toString("hex"));
  assert.equal(nodeHash(leafHash("x"), leafHash("y")), H(ONE, H(ZERO, utf8("x")), H(ZERO, utf8("y"))).toString("hex"));
  assert.equal(rootOf([]), H().toString("hex")); // MTH({}) = SHA-256()
  // every root and every proof for n = 1 to 33, against the recoded tree and the recoded RFC 9162 check
  for (let n = 1; n <= 33; n++) {
    const ls = lines.slice(0, n);
    const root = rootOf(ls);
    assert.equal(root, mthRef(ls.map(utf8)).toString("hex"), `root n=${String(n)}`);
    for (let m = 0; m < n; m++) {
      const line = ls[m] ?? "";
      const path = proofOf(ls, m);
      const raw = path.map((h) => Buffer.from(h, "hex"));
      assert.ok(verify9162(H(ZERO, utf8(line)), m, n, raw, Buffer.from(root, "hex")), `9162 n=${String(n)} m=${String(m)}`);
      assert.equal(verifyProof(line, m, n, path, root), true);
      // a count other than the tree's: the verdict of the recoded RFC 9162 check (path length bound to (index, count))
      assert.equal(verifyProof(line, m, n + 1, path, root), verify9162(H(ZERO, utf8(line)), m, n + 1, raw, Buffer.from(root, "hex")));
      if (n === 1) continue;
      assert.equal(verifyProof(ls[(m + 1) % n] ?? "", m, n, path, root), false);
      assert.equal(verifyProof(line, m, n, [leafHash("tampered"), ...path.slice(1)], root), false);
      assert.equal(verify9162(H(ZERO, utf8(line)), m, n, raw.slice(1), Buffer.from(root, "hex")), false);
    }
  }
  // RFC 6962 s2.1.3 example, seven leaves d0..d6 (FAITS L-1, L-2): a..f leaves of d0..d5, j leaf of d6; g = (a, b),
  // h = (c, d), i = (e, f), k = (g, h), l = (i, j); paths d0 [b, h, l], d3 [c, g, l], d4 [f, j, k], d6 [i, k].
  const seven = lines.slice(0, 7);
  const [a, b, c, dd, e, f, j] = seven.map((s) => H(ZERO, utf8(s)));
  assert.ok(a && b && c && dd && e && f && j);
  const g = H(ONE, a, b);
  const h = H(ONE, c, dd);
  const i = H(ONE, e, f);
  const k = H(ONE, g, h);
  const l = H(ONE, i, j);
  const hex = (xs: Buffer[]): string[] => xs.map((x) => x.toString("hex"));
  assert.deepEqual(proofOf(seven, 0), hex([b, h, l]));
  assert.deepEqual(proofOf(seven, 3), hex([c, g, l]));
  assert.deepEqual(proofOf(seven, 4), hex([f, j, k]));
  assert.deepEqual(proofOf(seven, 6), hex([i, k]));
  assert.equal(rootOf(seven), H(ONE, k, l).toString("hex"));
  // second preimage (M-M1): a 64-byte line equal to two node hashes must not give the root of four lines
  const four = lines.slice(0, 4);
  const n01 = nodeHash(leafHash(four[0] ?? ""), leafHash(four[1] ?? ""));
  const n23 = nodeHash(leafHash(four[2] ?? ""), leafHash(four[3] ?? ""));
  assert.notEqual(rootOf([Buffer.concat([Buffer.from(n01, "hex"), Buffer.from(n23, "hex")])]), rootOf(four));
  // odd count without duplicating the last leaf (M-M2): three lines give (0x01 || (a, b) || leaf c)
  assert.equal(rootOf(seven.slice(0, 3)), H(ONE, g, c).toString("hex"));
  assert.throws(() => proofOf(seven, 7), /out of range/);
  assert.throws(() => nodeHash("zz", leafHash("x")), /64 lowercase hex/);
  assert.equal(verifyProof(seven[0] ?? "", 0, 7, proofOf(seven, 0), "ZZ"), false);
});
