/**
 * HIKAE — S2 report rendering (ADR-M002 D10, CA-H2). Six recalculable blocks + the TWO
 * labelled blocks of decision (e): "real silence" (momentum ACTUALLY run) / "mechanism
 * demo" (9 states with declared scores + didactic oracle ACTUALLY run, marked "not a
 * product"). Headline subject to the vocabulary gate.
 *
 * D10 line under each figure: n, provenance label, date (injected), raw journal
 * hash. Discipline 09: no forbidden phrasing. Never "X % of correct fills"; we write
 * n, m, q̂, empirical coverage, abstention rate. A negative result = a result.
 */
import type { CampaignResult, MutantOutcome } from "./instrument.ts";
import type { S2Params } from "./run.ts";
import { MOMENTUM_4C_ID, ORACLE_DIDACTIQUE_ID } from "../predictor.ts";
import type { GateDecision } from "@monark/contracts";

function pct(x: number | null): string {
  return x === null ? "—" : `${(x * 100).toFixed(1)} %`;
}
function qh(r: CampaignResult): string {
  return "reason" in r.split ? `— (${r.split.reason})` : String(r.split.qhat);
}

export interface PredictorRunSummary {
  readonly nWarmup: number;
  readonly nPredictorNonEvaluable: number;
  readonly nPredictions: number;
}

export interface ReportInput {
  readonly harnessVersion: string;
  readonly params: S2Params;
  readonly s2a: CampaignResult;
  readonly s2bPooled: CampaignResult;
  readonly s2bByStratum: readonly CampaignResult[];
  readonly predictorRuns: { readonly momentum: PredictorRunSummary; readonly oracle: PredictorRunSummary };
  readonly mutants: readonly MutantOutcome[];
  /** DECLARED parameters of M2 + n evaluable (journalled under `M2-clean` / `M2-flip`). */
  readonly m2Params: { readonly seed: number; readonly n: number; readonly accuracy: number; readonly nCalib: number };
  readonly m2N: number;
  /** (e) "real silence" — `internal:momentum-4c` run (== pooled S2b). */
  readonly silenceReal: CampaignResult;
  /** (e) `internal:oracle-didactique` run on the same series (not a product). */
  readonly oracleReal: CampaignResult;
  readonly demo: readonly { readonly id: string; readonly decision: GateDecision }[];
  readonly journal: { readonly path: string; readonly digest: string; readonly lines: number };
}

export function renderS2Report(inp: ReportInput): string {
  const L: string[] = [];
  const p = inp.params;
  const d10 = (n: number, label: string) =>
    `_D10: n = ${n} · label = \`${inp.harnessVersion}/${label}\` · date = ${p.generatedOn} · journal sha256 = \`${inp.journal.digest.slice(0, 16)}…\`_`;

  L.push(`# S2 report — HIKAE (\`${inp.harnessVersion}\`)`);
  L.push("");
  L.push(
    "> **Disposable** harness (R-22). **Per-seed synthetic** fixtures (declared) — the J0 probe on " +
      "Coinbase (a product decision (a)) comes later. **A negative result = a result.** No figure " +
      "is presented as a probability of truth (09). Generated by `scripts/s2-report.mjs`; " +
      "the `s2_report_reproducible` test requires byte-for-byte equality with this file.",
  );
  L.push("");

  // Block 1 — Parameters (per campaign).
  L.push("## 1. Parameters");
  L.push(
    `Common: α = ${p.alpha} · n_min = ${p.nMin} · τ = ${p.tau} · route = synthetic fixtures (no network) · ` +
      `harness_version = \`${inp.harnessVersion}\` · generation date (injected) = ${p.generatedOn}.`,
  );
  L.push(
    `S2a: seed = ${p.s2a.seed} · n = ${p.s2a.n} · declared draw accuracy = ${p.s2a.accuracy} · n_calib = ${p.s2a.nCalib}.`,
  );
  L.push(
    `S2b: seeded candles (seed = ${p.s2b.seed}, n = ${p.s2b.nCandles}, close_time₀ = ${p.s2b.startCloseTime}, ` +
      `price₀ = ${p.s2b.startPrice}, max step = ${p.s2b.stepPct}, flat rate = ${p.s2b.flatRate}) · ` +
      `n_calib per stratum = ${p.s2b.nCalibPerStratum} · pooled n_calib = ${p.s2b.nCalibPooled}. ` +
      `Predictors ACTUALLY run: \`${MOMENTUM_4C_ID}\` (${inp.predictorRuns.momentum.nPredictions} \`Prediction\` emitted, ` +
      `${inp.predictorRuns.momentum.nWarmup} warmup windows, ${inp.predictorRuns.momentum.nPredictorNonEvaluable} without direction); ` +
      `\`${ORACLE_DIDACTIQUE_ID}\` (${inp.predictorRuns.oracle.nPredictions} emitted, ${inp.predictorRuns.oracle.nPredictorNonEvaluable} without direction).`,
  );
  L.push(
    `M2 (flipped-labels mutant): seed = ${inp.m2Params.seed} · n = ${inp.m2Params.n} · declared accuracy = ${inp.m2Params.accuracy} · ` +
      `n_calib = ${inp.m2Params.nCalib} · journalled campaigns \`M2-clean\` / \`M2-flip\`.`,
  );
  L.push("");

  // Block 2 — Raw journal.
  L.push("## 2. Raw journal");
  L.push(
    `One line per point and per campaign (columns: campaign, index, close_time, hour_utc, stratum, predictor_id, ` +
      `yhat, y, role ∈ {calib, holdout, excluded}, score, set, covered, action): [\`${inp.journal.path}\`](${inp.journal.path
        .replace(/^docs\//, "")}) — **${inp.journal.lines} lines**, sha256 = \`${inp.journal.digest}\`. ` +
      "Every figure below recomputes from this journal without trusting HIKAE (D10).",
  );
  L.push("");

  // Block 3 — S2a.
  L.push("## 3. S2a — plumbing (declared synthetic binary class)");
  L.push(
    `n_calib = ${inp.s2a.nCalib} · m = ${inp.s2a.mHoldout} · q̂ = ${qh(inp.s2a)} · ` +
      `empirical coverage (abstentions included) = ${pct(inp.s2a.coverageAll)} · ` +
      `abstention (τ=${p.tau}) = ${pct(inp.s2a.abstentionRate)} · non_evaluable = ${inp.s2a.nNonEvaluable}.`,
  );
  L.push(d10(inp.s2a.nEvaluable, "S2a"));
  L.push("");

  // Block 4 — S2b per stratum and pooled (real momentum).
  L.push(`## 4. S2b — beachhead \`btc-dir-15m\` (synthetic candles, \`${MOMENTUM_4C_ID}\` run)`);
  L.push("| stratum | n_calib | m | q̂ | coverage (abst. incl.) | abstention | action-cond. cov.* |");
  L.push("|---|---|---|---|---|---|---|");
  for (const s of inp.s2bByStratum) {
    L.push(
      `| ${s.label.replace(/^S2b-/, "")} | ${s.nCalib} | ${s.mHoldout} | ${qh(s)} | ${pct(s.coverageAll)} | ${pct(
        s.abstentionRate,
      )} | ${pct(s.coverageConditional)} |`,
    );
  }
  L.push(
    `| **pooled** | ${inp.s2bPooled.nCalib} | ${inp.s2bPooled.mHoldout} | ${qh(inp.s2bPooled)} | ${pct(
      inp.s2bPooled.coverageAll,
    )} | ${pct(inp.s2bPooled.abstentionRate)} | ${pct(inp.s2bPooled.coverageConditional)} |`,
  );
  L.push("");
  L.push("*\\* action-conditional coverage = desk figure, **NOT the CP guarantee** (H2.3).*");
  L.push(d10(inp.s2bPooled.nEvaluable, "S2b-pooled"));
  L.push("");

  // Block 5 — Mutants.
  L.push("## 5. Mutants (seeded negative controls)");
  L.push("| id | mutant | verdict |");
  L.push("|---|---|---|");
  for (const m of inp.mutants) L.push(`| ${m.id} | ${m.name} | ${m.pass ? "PASS" : "FAIL"} (${m.detail}) |`);
  L.push("");
  L.push(d10(inp.m2N, "M2-clean+M2-flip"));
  L.push("");

  // Decision (e) — two labelled blocks.
  L.push("## 6. Decision (e) — two labelled blocks");
  L.push(`### 6a. Real silence (\`${MOMENTUM_4C_ID}\`, run)`);
  L.push(
    `Momentum predictor on a random walk ≈ coin: n_calib = ${inp.silenceReal.nCalib} · m = ${inp.silenceReal.mHoldout} · ` +
      `q̂ = ${qh(inp.silenceReal)} · coverage = ${pct(inp.silenceReal.coverageAll)} · ` +
      `abstention = ${pct(inp.silenceReal.abstentionRate)} · commit = ${pct(inp.silenceReal.commitRate)}. ` +
      `Expected: **near-total calibrated silence** (at score 0/1, q̂=0 requires ≤ n − ⌈(n+1)(1−α)⌉ calibration errors: ` +
      `n=${inp.silenceReal.nCalib}, α=${p.alpha} ⇒ ≤ ${inp.silenceReal.nCalib - Math.ceil((inp.silenceReal.nCalib + 1) * (1 - p.alpha))}). ` +
      "The demo shows no position — that is the product (the right to hold no opinion).",
  );
  L.push(d10(inp.silenceReal.nEvaluable, "S2b-pooled"));
  L.push("");
  L.push(`### 6b. Mechanism demo (\`${ORACLE_DIDACTIQUE_ID}\` — **not a product**)`);
  L.push(
    `Didactic oracle (ŷ=y by construction) **run on the same series**: n_calib = ${inp.oracleReal.nCalib} · ` +
      `m = ${inp.oracleReal.mHoldout} · q̂ = ${qh(inp.oracleReal)} · coverage = ${pct(inp.oracleReal.coverageAll)} · ` +
      `abstention = ${pct(inp.oracleReal.abstentionRate)} · commit = ${pct(inp.oracleReal.commitRate)}. ` +
      "It makes the COMMIT path visible; it says nothing about the market.",
  );
  L.push(d10(inp.oracleReal.nEvaluable, "S2b-oracle"));
  L.push("");
  L.push(
    "The 9 mechanism states below are produced by the real `gate()` on verdicts with **declared scores** " +
      "(COMMIT: 47/50 calibration ⇒ q̂=0; DEFER: 25/50 ⇒ q̂=1) — **not** by the oracle (frozen digest, test 14):",
  );
  L.push("| state | action | reason | remaining budget |");
  L.push("|---|---|---|---|");
  for (const s of inp.demo) {
    L.push(`| ${s.id} | ${s.decision.action} | ${s.decision.reason} | ${s.decision.remaining_budget} |`);
  }
  L.push("");
  L.push(
    `**Headline** (on m = ${inp.silenceReal.mHoldout} hold-out, \`${MOMENTUM_4C_ID}\`): empirical coverage = ${pct(
      inp.silenceReal.coverageAll,
    )} vs 1−α = ${pct(1 - p.alpha)} · abstention (τ=${p.tau}) = ${pct(inp.silenceReal.abstentionRate)} — three figures, never merged.`,
  );
  L.push("");
  return L.join("\n");
}
