import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { writeFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildVerdict, buildSetRegion, serialize } from "../src/index.ts";
import { calibDigest, serializeVerdict } from "@monark/contracts";
import type { CoverageVerdict } from "@monark/contracts";
import { runS2 } from "../src/index.ts";

const SCORES = [0, 0, 1, 0, 1];

function baseVerdict(): CoverageVerdict {
  return buildVerdict({
    taskClass: "btc-dir-15m",
    method: "hac-cp",
    alpha: 0.1,
    scores: SCORES,
    region: buildSetRegion(["up"]),
    qhat: 0,
    abstain: false,
    reason: "covered",
    residual: ["assume:tls-notary"],
    producedAt: "2026-09-04T00:00:00Z",
    schemaVersion: "1.0.0",
  });
}

// Test 4 — a forbidden key (p_correct) in the verdict serialization ⇒ THROWS (frozen contract).
test("no_p_correct_field", () => {
  const clean = baseVerdict();
  assert.doesNotThrow(() => serialize(clean), "a clean verdict serializes");
  const poisoned = { ...clean, p_correct: 0.9 } as unknown as CoverageVerdict;
  assert.throws(() => serializeVerdict(poisoned), /p_correct|forbidden|unknown/i);
  // Deep injection (into the region) caught too.
  const deep = { ...clean, region: { kind: "set", labels: ["up"], label_schema: "up|down", confidence: 1 } } as unknown as CoverageVerdict;
  assert.throws(() => serializeVerdict(deep), /confidence|forbidden|unknown/i);
});

// Test 13 — verdict calib_digest == calibDigest(scores) (recalculability by reference).
test("calib_digest_matches_contracts", () => {
  const v = baseVerdict();
  assert.equal(v.calib_digest, calibDigest(SCORES), "calib_digest by reference (ADR-M001 C5)");
  // Cross-language oracle [0,1] (Phase 0).
  assert.equal(
    calibDigest([0, 1]),
    "1e47beee7f4175a863385dc2f9c8278138e35f0caa43a5467a523519f1e91081",
  );
});

// Test 12 — the error|COMMIT is a LABELLED desk figure (H2.3) + the vocab gate catches a forbidden phrasing.
test("commit_error_not_alpha_is_labelled", () => {
  // (a) the report (generated by the REAL runner, predictors run) labels the action-conditional
  // coverage "NOT the CP guarantee".
  const report = runS2().report;
  assert.match(report, /NOT the CP guarantee/, "the conditional coverage is labelled (H2.3)");
  // (b) the root vocab gate rejects a "NN % of ... correct" claim (exit 1).
  const root = join(import.meta.dirname, "..", "..", "..");
  // Outside the work tree (G2 Lot H corr. 3): `os.tmpdir()`, ephemeral directory, cleaned up.
  const scratch = mkdtempSync(join(tmpdir(), "hikae-vocab-"));
  const tmp = join(scratch, "hikae-vocab-mutant.md");
  writeFileSync(tmp, "Our agent achieves 73 % de fills corrects.\n");
  let exitCode = 0;
  try {
    execFileSync("node", [join(root, "scripts", "grep-forbidden.mjs"), tmp], { stdio: "pipe" });
  } catch (e) {
    exitCode = (e as { status?: number }).status ?? 1;
  }
  rmSync(scratch, { recursive: true, force: true });
  assert.equal(exitCode, 1, "a percent-correct claim ⇒ vocab gate fails");
});
